# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_first', models.CharField(max_length=100)),
                ('author_last', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=15)),
                ('publisher', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('owned_by', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(verbose_name='date item added')),
                ('updated_at', models.DateTimeField(verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='Item_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Item_type'),
        ),
        migrations.AddField(
            model_name='book',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Item'),
        ),
    ]
