# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=3)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned_to', models.IntegerField(blank=True, default=None, null=True)),
                ('loaned_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('due_back', models.DateTimeField(blank=True, default=None, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Item')),
            ],
        ),
    ]
