# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_comic_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
