# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170911_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
