# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170911_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookit', to='catalog.Item'),
        ),
    ]
