# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170911_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='month',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
