# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20171006_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_request',
            name='is_filled',
        ),
        migrations.AddField(
            model_name='item_request',
            name='filled_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
