# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20171006_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='item_request',
            name='is_accepted',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='item_request',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item_request',
            name='request_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Request_type'),
        ),
    ]
