# Generated by Django 2.0.2 on 2018-02-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_date_record_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date_record_notes',
            new_name='Date_record_note',
        ),
    ]
