# Generated by Django 2.0.2 on 2018-03-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180225_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_record',
            name='log_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
