# Generated by Django 2.0.2 on 2018-06-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180321_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date_record',
            unique_together={('log_date', 'journal')},
        ),
    ]
