# Generated by Django 2.1.7 on 2019-05-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20190203_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locality_name',
            field=models.CharField(max_length=256),
        ),
    ]
