# Generated by Django 2.1.7 on 2019-06-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20190528_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darksky_historical_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(blank=True, default=None, null=True)),
                ('max_uv_index', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
