# Generated by Django 2.1.7 on 2019-06-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_darksky_historical_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='darksky_historical_data',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Location'),
        ),
    ]
